### ISSUE TITLE
Static site indexing

### ISSUE THREAD

**Issue by MattBlissett** [gbif/gbif-asciidoctor-toolkit#8]
For the single page documents, the web browser's "Find in page" feature is often adequate.

For courses, a static site index with [Lunr.JS](https://lunrjs.com) would be better.

A recent commit https://github.com/gbif/gbif-asciidoctor-toolkit/commit/dc1db98cdcd025db0ca605adbc3ce927127e50bf builds the index, for example [lunr-index.js](https://docs.gbif-uat.org/course-data-mobilization/en/lunr-index.js), but an addition to the HTML is required to use it.

@MortenHofft, could you put together some UI? Even just by editing the HTML page https://docs.gbif-uat.org/course-data-mobilization/en/ ; I could then integrate the changes into the templates.  I tested by adding this to the end of the HTML:

```HTML
<script src="https://unpkg.com/lunr/lunr.js"></script>
<script type="text/javascript">
var d = fetch('lunr-index.js').then(response => response.json()).then(data => {
var idx = lunr.Index.load(data.index);
console.log("Search for precision", idx.search('precision'));
});
</script>
```

It returns data.  The metadata within the index may well need some adjustments.

If this works nicely, we can do something similar for the hosted portals — though they are a bit more complicated than these documents/courses.

**Comment by MortenHofft** [comment]
I guess it can be done many ways. How do you imagine this working?
* A suggest in the sidebar? then we need a library to handle accessibility, arrow navigation etc.
* A custom page with results - then perhaps we should probably handle url changes and have a search landing page url
* An overlay with a list of results

For the hosted portals, then we have Lunr search in a branch, but I cannot decide exactly how I want it to behave. Nor what the best way to build it is - my default would be node, but having a node step in the build seems silly in a Ruby project. I know there is a Ruby lunr lib - that could probably be used.

**Comment by MortenHofft** [comment]
I would recommend doing this using the final html. You will get search results for things that are not the main text of the page. Such as `next page: data management` . That probably isn't very useful. You want the next page. Perhaps you could find a way to take only what is in `<main>` or such?

**Comment by MattBlissett** [comment]
https://docs.gbif-uat.org/course-data-mobilization-matt/en/search.html?q=transect

I've rewritten the indexer to split the document into sections, so results link to the previous anchored heading.
